version: '3.8'

services:
  node:
    container_name: node
    image: "node:14.18.2"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app
    command: sh -c "npm install"
    #command: sh -c "npm run build"
    #command: sh -c "npm run start"